### ISSUE TITLE
Confirm which branch/tag the feedstock should point to...

### ISSUE THREAD

**Issue by gonuke** [conda-forge/cyclus-feedstock#18]
The Cyclus YAML file refers to 'master' for the feedstock - this doesn't seem right since we want the conda forge version to be our last release.  In theory these should always be the same, but it's not guaranteed in transient.

**Comment by scopatz** [comment]
Shoot! You are right, @gonuke. branch should be `1.5.0`.  Maybe it makes sense to remove the branch setting and instead rely on version. The branch was put there for testing and development purposes originally.

**Comment by scopatz** [comment]
This has been fixed
