### ISSUE TITLE
Archive this feedstock

### ISSUE THREAD

**Issue by xhochy** [conda-forge/cyclus-feedstock#71]
### Comment:

@conda-forge/cyclus This feedstock is unmaintained since years, any objections to archiving this?

**Comment by gonuke** [comment]
As it happens, we are in the middle of trying to get this project back into a stable build state and updating this build accordingly

**Comment by h-vetinari** [comment]
Be sure to remove as many hard pins and caps for third-party dependencies as possible, so that our infrastructure can take care of keeping the builds up to date (will be recompiled where necessary).

**Comment by h-vetinari** [comment]
Otherwise: great news, and best of luck! 🙃

**Comment by h-vetinari** [comment]
@gonuke, any update on this effort?

**Comment by gonuke** [comment]
We're nearly there...

**Comment by h-vetinari** [comment]
Hey @gonuke, what's the status on the cyclus revival?

**Comment by munkm** [comment]
hi @h-vetinari we are still working on this revival!

**Comment by bennibbelink** [comment]
Hi @h-vetinari, this feedstock has been updated.  Can this issue be closed?

**Comment by h-vetinari** [comment]
Well done! Yes it can!
