### ISSUE TITLE
Support MacOS

### ISSUE THREAD

**Issue by bennibbelink** [conda-forge/cyclus-feedstock#84]
https://github.com/cyclus/cyclus/pull/1814 put CI in place for MacOS (arm and intel) it should be possible to update this feedstock to build packages for macOS.

**Comment by gonuke** [comment]
Does the update in cyclus/cyclus#1814 rely on `slow` building for arm? Now that we have `decay` and `cram` for arm, can we use those instead?

**Comment by bennibbelink** [comment]
I installed `conda-forge/label/cyclus_dev::cyclus` on my machine and see lots of segfaults (even on `cyclus --help`).  When running `cyclus_unit_tests` the segfault occurs at `InfileConverters.JsonPyRoundTrip`, so I'm wondering if this has to do with how our cython libraries are being packaged and installed by conda.  I need to dig into this a bit more, but I wanted to document that these packages are not in a working state yet (on arm64 at least, I haven't been able to test on x86 mac)

**Comment by bennibbelink** [comment]
Closing this.  I think my local installation at `~/.local` was interfering with the conda-forge installation.  After cleaning the installation at `~/.local` I am able to install cyclus on my M1 Mac and run tests via the following:
1. `conda create -y -n test-env python==3.12 && conda activate test-env`
2. `conda install -y conda-forge/label/cyclus_dev::cyclus`
3. `which cyclus` (should report `$CONDA_PREFIX/bin/cyclus`)
4. `cyclus_unit_tests`
5. `conda install -y pytest pytables && cd <cyclus test dir> && python -m pytest`
